Revised r2modman profile sharing
LethalCompany/ModdingWiki pull request #31
Opened 2023-12-14 08:09 UTC by Boxofbiscuits97

## Profile Sharing
Pertains to issue #6  and #27 

Just a cleaned up version to be easily used on the wiki following the style of the other guides.

2023-12-14 08:12 UTC, ghotato commented
thanks a bunch!!

2023-12-15 00:32 UTC, ghotato commented
like this way better than mine, sweet and simple.

2023-12-15 06:05 UTC, legoandmars requested changes

2023-12-15 06:05 UTC, legoandmars commented on docs/user-guide/installation/installing-r2modman.md
> +1. Click **"Import/Update"** in the **Profile selction** area after selecting Lethal Company in r2modman.
typo in selection

2023-12-15 06:07 UTC, legoandmars commented
I do think this would be better as a separate page, but #29 changes how file structure works, so adding the page would have to be redone anyways

Once #29 is merged I'll probably add a bit more detail and separate this into a new page myself

in the meantime i'll just merge this as-is once the typo is fixed

2023-12-16 06:15 UTC, closed without merging