Improve config creation/syncing guides.
LethalCompany/ModdingWiki pull request #67
Opened 2024-01-03 01:13 UTC by Owen3H

- Replaces the stinky **BinaryFormatter** with [DataContractSerializer](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.datacontractserializer?view=net-8.0) - a more secure and slightly faster alternative that doesn't require a NuGet package or changing NET version.👍🏼 
- Config entries are no longer static and now use primitive types instead of `ConfigEntry` since it can't be serialized.
- Fixed the large config file problem by utilizing a new `SendMessage` that checks whether to fragment.
- Other general QoL (headings, formatting and examples)

Fixes #65

2024-01-03 01:20 UTC, 1A3Dev commented on docs/dev/intermediate/custom-config-syncing.md
> +            LogDebug(
```suggestion
            Plugin.Logger.LogDebug(
```

2024-01-09 22:05 UTC, legoandmars commented
Most of this looks good, I'm not sure I like having config values read from `.Value` on start though

This will prevent runtime editing of config values with future plugins and things like [ConfigurationManager](https://github.com/BepInEx/BepInEx.ConfigurationManager)

2024-01-09 22:07 UTC, legoandmars commented
When I have some time i'll see if I can figure out a non-insane way to retain using ConfigEntry with syncing

2024-01-23 15:02 UTC, Xilophor reviewed
Lgtm; only a few comments on some formatting/logging stuff.

2024-01-23 15:05 UTC, Xilophor commented on docs/dev/intermediate/custom-config-syncing.md
Consider changing some `LogInfo` to `LogDebug` to prevent normal players from having their log filled up.

2024-01-23 15:05 UTC, Xilophor commented on docs/dev/intermediate/custom-config-syncing.md
> +> Syncing doesn't work when I patch manually.
Consider changing this to `###` instead of `>` to make it more obvious

2024-01-23 15:05 UTC, Xilophor commented on docs/dev/intermediate/custom-config-syncing.md
>  > I am not seeing any logs from the request/receiver methods?
Same as above

2024-02-03 07:18 UTC, Owen3H commented
With the release of CSync, I have added a new section under **Programming APIs** updated the "Custom Config Syncing" page accordingly. Ideally, this should be merged and then #87 can be subsequently merged. 👍🏼

2024-02-10 17:30 UTC, Xilophor requested changes

2024-02-10 17:30 UTC, Xilophor commented on docs/.vitepress/config.mts
> +                      text: 'CSync',
Move this to below Configurable Company for correct alphabetical ordering

2024-02-10 17:30 UTC, Xilophor commented on docs/dev/apis/csync.md
> +- [Troubleshooting](/dev/csync/troubleshooting) - Reported issues and their solutions.
Fix these links to include `api/` after `/dev/` (ie `/dev/api/csync/...`)

2024-02-10 17:30 UTC, Xilophor commented on docs/dev/apis/csync/publishing.md
> +---
Since this file/article is so short, I recommend combining this into the usage-guide file

2024-02-10 17:30 UTC, Xilophor commented on docs/dev/apis/overview.md
> +- ⭐ [CSync by Owen3H]() is a compact library/API enabling mod authors to synchronize the host's configuration file with all other clients. [The wiki page on CSync]() will guide you through the proces
Put after ConfigurableCompany for correct alphabetical ordering

2024-02-10 17:30 UTC, Xilophor commented on docs/dev/apis/overview.md
> -- [ConfigurableCompany by Ansuz/Amrv](https://thunderstore.io/c/lethal-company/p/AMRV/ConfigurableCompany/) implements an in-game menu that allows developers to create file-dependant configurations i
Don't remove this & replace with a modified line; keep the original line

2024-02-10 17:30 UTC, Xilophor commented on docs/dev/intermediate/custom-config-syncing.md
>  # Custom Config Syncing
Please do not remove the contents of this file. We want to make sure that a way w/o APIs is provided for those pursuing this. You can, however, leave the section about the config syncing APIs and move that above the rest of the article, with text saying that an easier method is available.

2024-02-10 17:30 UTC, Xilophor commented on docs/dev/intermediate/custom-configs.md
> +    ).Value;
Doing this (.Value) does not support changing the config settings from any of the in-game config mods; please consider changing this back to allow changing config settings in-game via the config mods.

2024-03-08 23:06 UTC, closed without merging