Add Configurable Company API to wiki
LethalCompany/ModdingWiki pull request #87
Opened 2024-01-23 23:15 UTC by TheAnsuz

Adding [Configurable company API by Ansuz/AMRV](https://thunderstore.io/c/lethal-company/p/AMRV/ConfigurableCompany/) to the wiki since many developers may find it easier to understand it from here than from [thunderstore wiki](https://thunderstore.io/c/lethal-company/p/AMRV/ConfigurableCompany/wiki/) or [github wiki](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/wiki).

The wiki is part of the `Modding APIs` wiki section.

I reworked the contents of those existing wikis to provide more information in a friendly manner.

The API itself is not related to any other API in the wiki so I created both an overview and pages for each type of builder and complex feature that the developer might need to use the plugin correctly.

[Github](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API)
[Thunderstore](https://thunderstore.io/c/lethal-company/p/AMRV/ConfigurableCompany/)

2024-02-05 17:29 UTC, Xilophor requested changes
Just needs some minor formatting & grammar changes

2024-02-05 17:29 UTC, Xilophor commented on docs/dev/apis/configurable-company.md
> +next: false
set to true for easy linking to the next page (developing pages)

2024-02-05 17:29 UTC, Xilophor commented on docs/.vitepress/config.mts
> +                          text: 'Developing pages',
use Title Case for the article titles in the sidebar

2024-02-05 17:29 UTC, Xilophor commented on docs/dev/apis/configurable-company/developing-pages.md
> +prev: false
set to true to easily go back to the API's overview page

2024-02-05 17:29 UTC, Xilophor commented on docs/dev/apis/configurable-company/developing-categories.md
> +description: How to create categories for your plugin and how to use them.
add 'Configurable Company' to this
...create Configurable Company categories...

2024-02-05 17:29 UTC, Xilophor commented on docs/dev/apis/configurable-company/developing-configs.md
> +description: How to create configurations for your plugin and how to use them.
add 'Configurable Company' to this
...create Configurable Company configurations...

2024-02-05 17:29 UTC, Xilophor commented on docs/dev/apis/configurable-company/developing-pages.md
> +description: How to create pages for your plugin and how to use them.
add 'Configurable Company' to this
...create Configurable Company pages...

2024-02-05 17:29 UTC, Xilophor commented on docs/dev/apis/configurable-company/developing-categories.md
> +`Build()` Will create the category. It will not be created until the method is called (However as mentioned above, the method will called automatically if you assign the creation to a category).
change Will to will

2024-02-05 18:27 UTC, TheAnsuz commented
Updated :)

2024-02-06 08:49 UTC, Owen3H commented on docs/dev/apis/configurable-company.md
> +    public class YourPlugin : BaseUnityPlugin {
Missing closing bracket

2024-02-06 08:51 UTC, Owen3H commented on docs/dev/apis/configurable-company.md
> +    BepInDependency.DependencyFlags.HardDependency)] // [!code ++]
Spanning this across multiple lines probably isn't the best bet for readability.

2024-02-09 04:27 UTC, Xilophor approved these changes
Lgtm

2024-02-09 04:27 UTC, merged